sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t eyalsegal72/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eyalsegal72/docker-react npm run test 